services:
  back-office:
    build:
      context: ./BackOffice
      dockerfile: Dockerfile
    container_name: zavamisy-back-office
    ports:
      - "8001:80"
    volumes:
      - ./BackOffice:/var/www/html
    environment:
      - APP_ENV=development
      - DB_DRIVER=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=zavamisy
      - DB_USER=zava_user
      - DB_PASSWORD=secret
    networks:
      - zavamisy-network

  front-office:
    build:
      context: ./FrontOffice
      dockerfile: Dockerfile
    container_name: zavamisy-front-office
    ports:
      - "8000:80"
    volumes:
      - ./FrontOffice:/var/www/html
    environment:
      - APP_ENV=development
    networks:
      - zavamisy-network

  db:
    image: postgres:16-alpine
    container_name: zavamisy-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=zavamisy
      - POSTGRES_USER=zava_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./BackOffice/sql/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./BackOffice/sql/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - zavamisy-network

networks:
  zavamisy-network:
    driver: bridge

volumes:
  pgdata:
